In [1]:
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier
import numpy as np
import pandas as pd
from sklearn.datasets import load_iris

In [2]:
iris = load_iris()
dir(iris)

['DESCR',
 'data',
 'feature_names',
 'filename',
 'frame',
 'target',
 'target_names']

In [5]:
X = pd.DataFrame(iris.data, columns=iris.feature_names)
X.head()

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0                5.1               3.5                1.4               0.2
1                4.9               3.0                1.4               0.2
2                4.7               3.2                1.3               0.2
3                4.6               3.1                1.5               0.2
4                5.0               3.6                1.4               0.2

In [6]:
y = iris.target
y

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [8]:
from sklearn.model_selection import KFold
kf = KFold(n_splits=3)

In [ ]:
from sklearn.model_selection import cross_val_score

In [40]:
def get_scores(model, X, y):
    return cross_val_score(model, X, y, cv=5)

In [41]:
scores_lr = get_scores(LogisticRegression(max_iter=3000), iris.data, iris.target)
scores_lr

array([0.96666667, 1.        , 0.93333333, 0.96666667, 1.        ])

In [42]:
scores_lr.mean()

0.9733333333333334

In [43]:
scores_svm = get_scores(SVC(), iris.data, iris.target)
scores_svm

array([0.96666667, 0.96666667, 0.96666667, 0.93333333, 1.        ])

In [44]:
scores_svm.mean()

0.9666666666666666

In [45]:
scores_rf = get_scores(RandomForestClassifier(), iris.data, iris.target)
scores_rf

array([0.96666667, 0.96666667, 0.93333333, 0.93333333, 1.        ])

In [46]:
scores_rf.mean()

0.96

In [22]:
# for train_index, test_index in kf.split(iris.data):
#     X_train, X_test, y_train, y_test = pd.DataFrame(iris.data[train_index]), pd.DataFrame(iris.data[test_index]), \
#         iris.target[train_index], iris.target[test_index]
#     print(get_score(LogisticRegression(), X_train, X_test, y_train, y_test))
#     print(get_score(SVC(), X_train, X_test, y_train, y_test))
#     print(get_score(RandomForestClassifier(), X_train, X_test, y_train, y_test))